force-app/main/default/objects/Campanha2__c/fields/TitleMSG__c.field-meta.xml
<CustomField>
    <fullName>TitleMSG__c</fullName>
    <label>TitleMSG</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campanha2__c/fields/WelcomeMSG__c.field-meta.xml
<CustomField>
    <fullName>WelcomeMSG__c</fullName>
    <label>WelcomeMSG</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead2__c/fields/Campanha2__c.field-meta.xml
<CustomField>
    <fullName>Campanha2__c</fullName>
    <label>Campanha2</label>
    <referenceTo>Campanha2__c</referenceTo>
    <relationshipLabel>Lead2s</relationshipLabel>
    <relationshipName>Lead2s</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Lead2triggerTest.cls
@isTest
public with sharing class Lead2triggerTest {

    @isTest
    static void test() {
        Campanha2__c newCapanha = new Campanha2__c();
        newCapanha.Name = 'teste';
        newCapanha.TitleMSG__c = 'aaa';
        newCapanha.WelcomeMSG__c = 'aaa';
        insert newCapanha;

        Lead2__c newLead = new Lead2__c();    
        newLead.Name = 'teste';
        newLead.Email__c = 'teste@teste.com';
        newLead.Campanha2__c = newCapanha.Id;
        insert newLead;
    }

}